POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"7a9d6f2e-3b4c-4d8e-9a2b-7a9d6f2e3b4c",
    "price": 180.95,
    "tax": 3.25
}

###

GET  http://localhost:8000/orders HTTP/1.1
Host: localhost:8000
Content-Type: application/json
